# Generated by Django 4.0.4 on 2022-06-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_alter_photo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
