# Generated by Django 4.0.4 on 2022-07-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_post_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ex_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
