# Generated by Django 4.0.4 on 2022-07-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_post_ex_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ex_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
