# Generated by Django 4.0.4 on 2022-07-03 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_alter_post_ex_link_alter_post_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Project',
        ),
    ]
