# Generated by Django 4.0.1 on 2022-07-06 18:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_rename_post_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('more_about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('more_about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
